- name: Install packages
  hosts: all
  become: yes
  vars:
    apt_packages:
      - python3
      - python3-venv
      - python3-pip
      - git
      - unzip
      - openjdk-11-jdk
      - firewalld
  tasks:
    - name: Update apt cache and install packages
      apt:
        name: "{{ apt_packages }}"
        state: present
        update_cache: yes
        cache_valid_time: 3600
