- name: Copy app code
  hosts: flask
  become: yes
  tasks:
    - name: Create app directory
      file:
        path: /opt/flask_app
        state: directory

    - name: Copy Flask app
      copy:
        src:  ../files/flask.py
        dest: /opt/flask_app/

    - name: Create venv for Flask
      command: python3 -m venv /opt/flask_app/venv

    - name: Copy Flask requirements
      copy:
        src: ../files/requirements.txt   
        dest: /opt/flask_app/requirements.txt

    - name: Install Flask dependencies
      pip:
        requirements: /opt/flask_app/requirements.txt
        virtualenv: /opt/flask_app/venv
        virtualenv_command: python3 -m venv

- name: Copy subscriber code
  hosts: subscriber
  become: yes
  tasks:
    - name: Create subscriber directory
      file:
        path: /opt/subscriber
        state: directory

    - name: Copy subscriber script
      copy:
        src: ../files/subscriber.py
        dest: /opt/subscriber.py

- name: Copy publisher code
  hosts: publisher
  become: yes
  tasks:
    - name: Create publisher directory
      file:
        path: /opt/publisher
        state: directory

    - name: Copy publisher script
      copy:
        src: ../files/publisher.py
        dest: /opt/publisher/publisher.py
        mode: '0755'

## Generated with the help of ChatGPT