---

- name: Install Docker for cc user
  hosts: k8s_cluster
  become: yes
  tasks:
    - name: Update apt package cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install prerequisites
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Add Docker GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Install Docker
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: yes

    - name: Start and enable Docker
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add cc user to docker group
      ansible.builtin.user:
        name: cc
        groups: docker
        append: yes

    - name: Test Docker installation
      ansible.builtin.shell:
        cmd: docker run --rm hello-world
      become_user: cc
      register: docker_test

    - name: Show Docker test result
      ansible.builtin.debug:
        var: docker_test.stdout

- name: Install Docker on Ubuntu
  hosts: k8s_cluster
  become: yes
  tasks:
    - name: Update apt package cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install prerequisites
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Add Docker GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Install Docker
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: yes

    - name: Start and enable Docker
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add user to docker group
      ansible.builtin.user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Test Docker installation
      ansible.builtin.shell:
        cmd: docker run --rm hello-world
      register: docker_test
      ignore_errors: yes

    - name: Show Docker test result
      ansible.builtin.debug:
        var: docker_test.stdout

- name: Install cri-dockerd
  hosts: k8s_cluster
  become: yes
  tasks:
    - name: Download cri-dockerd
      ansible.builtin.get_url:
        url: https://github.com/Mirantis/cri-dockerd/releases/download/v0.3.4/cri-dockerd_0.3.4.3-0.ubuntu-jammy_amd64.deb
        dest: /tmp/cri-dockerd.deb
        mode: '0644'

    - name: Install cri-dockerd package
      ansible.builtin.apt:
        deb: /tmp/cri-dockerd.deb

    - name: Start and enable cri-dockerd service
      ansible.builtin.systemd:
        name: cri-docker
        state: started
        enabled: yes
        daemon_reload: yes

    - name: Test cri-dockerd socket
      ansible.builtin.wait_for:
        path: /run/cri-dockerd.sock
        state: present
        timeout: 30

    - name: Test cri-dockerd with crictl
      ansible.builtin.shell:
        cmd: crictl --runtime-endpoint=unix:///run/cri-dockerd.sock version
      register: cri_test
      ignore_errors: yes

    - name: Show cri-dockerd test result
      ansible.builtin.debug:
        var: cri_test.stdout